name: XingWoo TypeSpec CI

on:
  push:
    branches: [main]

jobs:
  build-project:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run build for TSP
        run: npm run build --if-present
      - name: dir
        run: dir
      - name: 'Upload Artifact TSP openAPI 3.0'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact-openapi
          path: /home/runner/work/typespec-poc/typespec-poc/tsp-output/
          retention-days: 5
  release-project:
    runs-on: ubuntu-latest
    needs: build-project
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/download-artifact@v3
        name: download
        with: 
          name: my-artifact-openapi
      - name: Test artifact download
        run: ls -R
  test-project-artifact:
    runs-on: ubuntu-latest
    needs: build-project
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/download-artifact@v3
        name: download
        with: 
          name: my-artifact-openapi
      - name: Test artifact download
        run: ls -R
  release-to-apim:
    runs-on: ubuntu-latest
    needs: build-project
    permissions:
      id-token: write
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/download-artifact@v3
        name: downloads
        with: 
          name: my-artifact-openapi
      - name: Azure Login directory
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
            enable-AzPSSession: true

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.48.1
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt